name: Build and deloy on dev


on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
#    - run: npm test
#      env:
#        CI: true
    - uses: actions/checkout@master
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.webserverhostname }}
        username: ${{ secrets.webserverusername }}
        key: ${{ secrets.webserversshkeyprivate }}
        source: "."
        target: "/srv/www/2020.capitoledulibre.org/htdocs"
